AccountsService.get_by_address() couple of fixes
Fix TypeError on get_by_address() with no match
The error was:
TypeError: exceptions.KeyError does not take keyword arguments

Also unit test get_by_address() multiple matches and no match.
Introduced `dev_requirements.txt` file.
Increases coverage and requires pytest-mock additional dep.